context:
  version: 2.0.3

package:
  name: r-magrittr
  version: ${{ version }}

source:
  url: https://cran.r-project.org/src/contrib/magrittr_${{ version }}.tar.gz
  sha256: a2bff83f792a1acb801bfe6330bb62724c74d5308832f2cb6a6178336ace55d2

build:
  number: 0
  noarch: generic
  script:
    # - print("Hello World!", quote = FALSE)
    - R CMD INSTALL --build .
    # - write("MIT", file = "MIT")

requirements:
  build:
    - r-base
  host:
    - r

tests:
  - r:
      uses:
        - magrittr

about:
  license: MIT
  license_file:
    # - MIT
  summary: A Forward-Pipe Operator for R
  homepage: https://magrittr.tidyverse.org/